version: 2
jobs:
  build:
    working_directory: /go/src/github.com/triggermesh/tm
    docker:
      - image: circleci/golang
    steps:
      - run:
          name: Install gcloud SDK
          command: |
            echo "deb http://packages.cloud.google.com/apt cloud-sdk-stretch main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            sudo apt-get update -y
            sudo apt-get install google-cloud-sdk -y
            go get -u golang.org/x/lint/golint
            go get -u github.com/Masterminds/glide
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run:
          name: Setup credentials
          command: |
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
            mkdir -p ${HOME}/.tm/
            cp ${HOME}/.kube/config ${HOME}/.tm/config.json
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run:
          name: Run lint
          command: make lint
      - run:
          name: Run fmt-test
          command: make fmt-test
      - run:
          name: Run vet
          command: make vet
      - run:
          name: Run unit tests
          no_output_timeout: 15m
          command: mkdir -p ${OUTPUT_DIR} && make test
          environment:
            OUTPUT_DIR: /tmp/test-results/
      - store_test_results:
         path: /tmp/test-results/
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

  release:
    docker:
      - image: circleci/golang
    steps:
      - run:
          name: Build binaries
          command: make release
          environment:
            DIST_DIR: /tmp/dist/
            GIT_TAG: ${CIRCLE_TAG}
      - run:
          name: "Install github-release tool"
          command: go get github.com/meterup/github-release
      - run:
          name: "Publish Release on GitHub"
          command: |
            # delete the release if it exists (it does not delete the tag, only the github release and associated artifacts)
            github-release delete -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -t ${CIRCLE_TAG} 2>/dev/null ||:
            github-release release -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -t ${CIRCLE_TAG} -d "tm ${CIRCLE_TAG}"
      - run:
          name: "Upload Release Artifacts"
          command: |
            for f in $(find /tmp/artifacts/ -type f); do
              github-release upload -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -t ${CIRCLE_TAG} -n "$(basename ${f})" -f "${f}"
            done

workflows:
  version: 2
  main:
    jobs:
      - build:
          context: staging
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
